/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as src from "./src";
export type { src };
export * as factories from "./factories";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { Cocodrop } from "./src/Cocodrop";
export { Cocodrop__factory } from "./factories/src/Cocodrop__factory";
